First screen done
rodionchykerenda/WeatherApp pull request #1
Opened 2021-03-29 14:53 UTC by rodionchykerenda

2021-03-29 15:48 UTC, ovcharukmaks requested changes

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/LocationSearchTableViewController.swift
> +    func mapSearchDelegate(didSelectItem item: String)
В делегатах даже в таком кейсе нужно передавать sender. Даже если мы ее не будет использовать

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/LocationSearchTableViewController.swift
> +            guard !result.title.contains("Street"), !result.title.contains("Square") else { return false }
Гварды можно объединить в один

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/LocationSearchTableViewController.swift
> +        guard searchController.searchBar.text != "" else {
isEmpty свойствo

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/LocationSearchTableViewController.swift
> +        guard searchController.searchBar.text != "" else {
И у нас уже есть переменная searchBarText, зачем мы обращаемся опять к серч контроллеру и серч бару?

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/LocationSearchTableViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "cell")!
Жееееж, форс анрап

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/LocationSearchTableViewController.swift
> +    var searchTerms: [String] = [] {
Приватным не должно быть?

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/MapViewController.swift
> +    func mapViewController(didAddLocation: (longitude: Double?, latitude: Double?))
Тут тоже передаем sender

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/MapViewController.swift
> +            if DataBaseManager.instance.isSelected(latitude: latitude, longitude: longitude) {
гвард

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/MapViewController.swift
> +
лишний пропуск

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/MapViewController.swift
> +            placeMark = placemarks?[0]
Это точно безопасно? Там всегда будет первый элемент?
Нужно проверить и сделать безопасно, чтобы там точно был элемент и оно не крашнулось

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/MapViewController.swift
> +        if let tapRecognizer = tapRecognizer {
Я понимаю, почему ты его тут написал)
Чтобы здесь не писать if let, то можно создать сначала локальную переменную и потом ее засетапить в проперти, и сделать mapView.addGestureRecognizer

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/MapViewController.swift
> +        let button = UIButton(frame: CGRect(x: (view.frame.width / 2) - 100, y: view.frame.height - 100, width: 200, height: 40))
Давай это в сторике сделаем, а то какие-то фреймы, цифры, непонятно

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/MapViewController.swift
> +        let alert = UIAlertController(title: "Empty response", message: "Sorry, we dont have this place in our DataBase. Try to find some other places close to this location.", preferredStyle: .alert
В требованиях писал "Приложение будет доступно с 13 оси, только портретная ориентация. Добавить возможность локализации, но пока что сделать только английский язык.", но возможно оно потерялось в куче текста
Все дело в том, чтобы сразу использовать локализированный строки, а не такие текстовки. Карточку в трелло добавил

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationTableViewCell.swift
> +        spinner = UIActivityIndicatorView(frame: CGRect(x: self.frame.size.width - 70, y: self.frame.size.height - 70, width: 50, height: 50))
Даже такое тоже добавляем в сторик
Очень неудобно, когда половина вещей в сторике, половина тут на фреймах и как это саппортить - хз

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationWeatherManager.swift
> +            let session = URLSession(configuration: .default)
Можно лучше хранить сессию в проперти и не создавать каждый раз?

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationWeatherManager.swift
> +        if let url = URL(string: "https://api.openweathermap.org/geo/1.0/direct?q=\(correctCityName)&limit=1&appid=73894ed3d982502db57069e27afdfc6b") {
гвард

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationWeatherManager.swift
> +protocol SelectedLocationWeatherManagerDelegate: class {
Понимаю, зачем тут делегат, но у меня вопрос. Если у нас этот нетворк менеджер будет использовать на двух скринах (а это вполне обычное действие), то как мы будем это хендлить?
(может все таки кложуру :) для начала?)

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationWeatherManager.swift
> +                if let safeData = data {
гвард

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationWeatherManager.swift
> +                        return
Точно нужен ретурн тут?)

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationWeatherManager.swift
> +        if let url = URL(string: "https://api.openweathermap.org/geo/1.0/reverse?lat=\(location.latitude)&lon=\(location.longitude)&limit=1&appid=73894ed3d982502db57069e27afdfc6b") {
Дальше такие же комменты, как и в предыдущем методе, поэтому пересмотри

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +    @IBOutlet weak var backgroundView: UIView!
Прийват должен быть

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +
Лишний пропуск

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +        guard dataSource[0].cityName != "Current Location" else {
А если датасорс будет пустой?
И очень плохо завязывать на текстовки, потому что:
1 они могут меняться
2 они могут локализироваться

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +        let button = UIButton(frame: CGRect(x: view.frame.width - 100, y: view.frame.height - 120, width: 80, height: 80))
Давай все таки вещи добавлять в сторике
И если не в сторике, то с использованием автолайаута (если в этом есть крайняя необходимость и иначе никак)

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +    func loadAll() {
Непонятное название метода, будто грузим весь интернет

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +        for item in dataSource {
Давай будем использовать более модные штуки (ф-ии высшего порядка), мы же прогрессивные ребята:

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +        if let location = locations.last {
гваард

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +        for i in 0..<dataSource.count {
ф-ии высшего порядка

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +                DataBaseManager.instance.delete(city: DataBaseManager.instance.getCities()[indexPath.row])
чтобы везде не писать DataBaseManager.instance, можно положить менеджер в проперти и обращать к ней просто через *dataBaseManager."

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +            self.contentTableView.refreshControl?.endRefreshing()
Мне кажется, что оно тут неправильно стоит. Метод  loadAll не сразу же загрузит данные, он асинхронный

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationWeatherManager.swift
> +struct SelectedLocationWeatherManager {
Название менеджера не очень соответствующее. Похоже больше на какой-то WeatherNetworkManager

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationWeatherManager.swift
> +extension SelectedLocationWeatherManagerDelegate {
Если протокол и его экстешен большой (ну типа не один метод), то есть смысл вынести в отдельный файл рядом

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/DataManager.swift
> +class DataManager {
Если честно, то больше похож на какой-то Helper или Mapper, чем на менеджер
Можно его вынести в отдельную папку и сделать не синглтоном, а статические методы

2021-03-29 15:48 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +    @IBAction func locationPressed(_ sender: UIButton) {
Лучше добавлять еще locationButtonPressed

2021-03-30 09:20 UTC, rodionchykerenda commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +            self.contentTableView.refreshControl?.endRefreshing()
По идее же правильно
Он же не должен стоять в мейне
По тригеру рефреш контрола лоадит все

2021-03-30 09:22 UTC, rodionchykerenda commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +        for i in 0..<dataSource.count {
Они immutable вроде

2021-03-30 09:33 UTC, rodionchykerenda commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +        let button = UIButton(frame: CGRect(x: view.frame.width - 100, y: view.frame.height - 120, width: 80, height: 80))
Гуглил много по поводу overlay объектов(тут кнопки же на тейбл вью лежат) все нашел только кодом.
Если констрейнты заюзаю но программно, это ок?

2021-03-30 10:27 UTC, rodionchykerenda commented on WeatherApp/WeatherApp/SelectedLocationWeatherManager.swift
> +protocol SelectedLocationWeatherManagerDelegate: class {
Могу создать Нетворк менеджер новый для работы с следующим флоу и там делать с кложурами?
Просто тут половину кода нужно будет менять
(если критично сделаю сразу)

2021-03-30 10:44 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +            self.contentTableView.refreshControl?.endRefreshing()
Тут вопрос не мейна, а в том, что у тебя контрол спрячется сразу, а загрузка в loadAll будет продолжаться дальше

2021-03-30 10:45 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationsViewController.swift
> +        let button = UIButton(frame: CGRect(x: view.frame.width - 100, y: view.frame.height - 120, width: 80, height: 80))
Если констрейнты программно - уже лучше, но точно не фреймами)

2021-03-30 10:46 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationWeatherManager.swift
> +protocol SelectedLocationWeatherManagerDelegate: class {
Просто нужно понимать, какую ты выбрал архитектуру. У тебя не должно быть такого, что ты в каждом менеджере будешь создавать URLSession. Если ты в новом планируешь ее заново создавать и хранить - уже плохо и нужно переделывать.
Лучше сейчас текущий менеджер переделать, это не так долго будет, но хотя бы правильнее и расширяемо станет

2021-04-01 09:18 UTC, closed without merging