Second Screen Logic Added
rodionchykerenda/WeatherApp pull request #3
Opened 2021-04-06 09:50 UTC by rodionchykerenda

2021-04-06 11:04 UTC, ovcharukmaks requested changes

2021-04-06 11:04 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationWeatherManager.swift
> +            if let safeData = data {
guard let

2021-04-06 11:04 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/SelectedLocationWeatherManager.swift
> +        guard let  encodedURL = fullUrlString.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed),
лишний пробел перед encodedURL

2021-04-06 11:04 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/DataBaseManager.swift
> +            if !incidents.isEmpty {
guard

2021-04-06 11:04 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/DataBaseManager.swift
> +                for result: NSManagedObject in incidents {
forEach

2021-04-06 11:04 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/DataBaseManager.swift
> +            if let selectedLongitude = $0.longitude,
guard let

2021-04-06 11:04 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/AppDelegate.swift
> +        let navigationController = UINavigationController(rootViewController: selectedLocationVC)
Лучше сделать какой-то метод start и т.д.

2021-04-06 11:04 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/DataBaseManager.swift
> +        return cities
пустые пропуски до и после do, по аналогии с if, switch, for и т.д.
Че свифт линт не ругается. Попробуй погуглить и сказать, должно ли оно ругаться на это и похожие штуки. Вот как у нас в пт было, что он не ругался на форс анврап, попробуй поискать и напиши мне про успехи

2021-04-07 13:29 UTC, maksimovcharukz approved these changes

2021-04-07 14:08 UTC, merged