Second Screen UI Done
rodionchykerenda/WeatherApp pull request #4
Opened 2021-04-09 15:42 UTC by rodionchykerenda

2021-04-09 16:02 UTC, ovcharukmaks requested changes

2021-04-09 16:02 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/DetailWeatherViewController.swift
> +        case 0:
Точно так же и здесь. Сегодня у нас 3 секции и эта ячейка первая, а завтра она будет вторая и нужно будет по коду искать места, где менять. Потому что ты несколько раз пишешь switch-case: numberOfRowsInSection, heightForRowAt. Если добавится логика, то еще будет места, где будет switch-case и везде мы завязываемся на 0,1,2.. 

Задача: сделать нашу таблицу с секциями очень гибкую. Чтобы мы могли менять секции местами, добавлять, убирать и потом могли легко это все саппортить

2021-04-09 16:02 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/DetailWeatherViewController.swift
> +                cell.styleUI()
Может это лучше делать в методе awakeFromNib у ячейки?

2021-04-09 16:02 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/MainCurrentWeatherTableViewCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
Если ничего нет же, то удаляем, помнишь это :)

2021-04-09 16:03 UTC, rodionchykerenda commented on WeatherApp/WeatherApp/MainCurrentWeatherTableViewCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
Блин, я так старался следить за этим
На скорую руку допиливал, сори

2021-04-12 07:20 UTC, rodionchykerenda commented on WeatherApp/WeatherApp/DataManager.swift
> +        dateFormater.dateFormat = "EEEE, MMM d, yyyy"
Т е по факту в хэлпере должна быть пока что только работа с форматерами данных
Или методы по получению вью модели с кодабл модели тоже нужно туда вынести?

2021-04-12 07:23 UTC, rodionchykerenda commented on WeatherApp/WeatherApp/DetailCurrentWeatherTableViewCell.swift
> +        backView.backgroundColor = UIColor(named: "BottomBackgroundColor")
Я думаю что можно сделать extension String'a ы и записать туда статик константу названия цвета
Или лучше сделать extension чего-то другого и возвращать сразу цвет?

2021-04-12 07:26 UTC, rodionchykerenda commented on WeatherApp/WeatherApp/DetailWeatherViewController.swift
> +        case 0:
"С секциями" это ключевое слово?
Просто у меня же пока 1 секция с 3 клеточками
Пока из того что я придумал это делать массив Any или вообще протокол какой-то кастовый придумать
И downcastить в ифах
По идее так же гибко будет

2021-04-12 07:54 UTC, rodionchykerenda commented on WeatherApp/WeatherApp/DataManager.swift
> +        let windSpeed = String(Int(networkModel.current.windSpeed)) + "m/s"
Мне кажется что пока не нужно задумываться об этом
Я планировал делать этот функционал практически в последнюю очередь

2021-04-12 07:57 UTC, rodionchykerenda commented on WeatherApp/WeatherApp/DetailWeatherHandler.swift
> +    var dataSource = [DetailWeatherViewModel]()
Я релоажу всю таблицу
И соответсвенно все коллекции в таблице релоадятся
Я сделал приватным сет и написал метод сэттера но пока не хочу передавать туда саму коллекцию
Типо она же есть в методах которые нужны.

2021-04-12 09:09 UTC, ovcharukmaks commented on WeatherApp/WeatherApp/DetailWeatherViewController.swift
> +        case 0:
С секциями - это не ключевое слово, но подход, про который я говорю может работать и с ними
Сейчас по сути секция - это будет твоя конкретная ячейка (как у тебя сейчас 0, 1, 2) и нужно с ними работать динамически, как я отписал
Протокол и даункастить в ифах - такое себе. Потому что можно и без ифов сделать

2021-04-12 09:11 UTC, rodionchykerenda commented on WeatherApp/WeatherApp/DetailWeatherViewController.swift
> +        case 0:
Можно наверное еще сделать протокол с полем какого-то енама который будет собственно говорить что это за клеточка и по ней свитчить

2021-04-12 16:06 UTC, ovcharukmaks approved these changes

2021-04-13 07:28 UTC, merged